# Generated by Django 2.2.10 on 2020-04-28 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('searchscraper', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='search',
            options={'verbose_name_plural': 'searches'},
        ),
    ]
